apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: resource-event-source
spec:
  type: resource
  resource:
    example:
      # namespace to listen events within
      namespace: argo-events
      # resource group
      group: argoproj.io
      # resource version
      version: v1alpha1
      # resource kind
      resource: workflows
      # types of events to listen for.
      # possible values are ADD, DELETE, UPDATE
      eventTypes:
        - ADD
      # Filters to apply on watched object.
      # If you apply filter, then the internal event informer will only monitor objects that pass the filter.
      # Optional
      filter:
        labels:
          name: my-workflow

#    # create event when a pod is created before 2019-03-27T010:52:32Z
#    example-with-created-by-filter:
#      namespace: "argo-events"
#      group: argoproj.io
#      version: v1alpha1
#      resource: workflows
#      eventTypes:
#        - ADD
#      filter:
#        createdBy: "2019-04-06T12:52:11Z"

#    # filters object that has prefix "my-"
#    example-with-prefix:
#      namespace: "argo-events"
#      group: argoproj.io
#      version: v1alpha1
#      resource: workflows
#      eventTypes:
#        - ADD
#      filter:
#        prefix: my-
